import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const html = await readFile(new URL('../confinex.html', import.meta.url), 'utf8');
assert.match(html, /confinex-supabase-ponte-inline\.js\?v=/);
assert.match(html, /confinex-app\.mobile\.js\?v=/);
assert.doesNotMatch(html, /<\/script>\\n\s*<script/);
assert.match(html, /id="root"/);
assert.match(html, /__CONFINEX_BUILD/);
globalThis.window = {};
await import('../js/confinex-supabase-ponte.mjs');
const adaptador = await import('../js/confinex-supabase-adaptador.mjs');
const sim = await adaptador.iniciarAvaliacao({ dados: { codigo: 'CF', grupoOrigemNome: 'Teste', premissas: {}, resultado: {} } });
assert.equal(sim.modo, 'simulacao');
console.log('Ponte Supabase Confinex: 7 verificações aprovadas');
